<?php
/**
 * Shared package contract (generated from ctw-contract.json).
 *
 * AUTO-GENERATED by scripts/sync-contract.mjs — do not edit by hand.
 * Source: packages/schema/contract/ctw-contract.json
 *
 * @package CTW_Native
 */

namespace CTW_Native\Contract;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Single source for Free widgets, core plugins, snippets, and installer mains.
 */
final class Package_Contract {

	/**
	 * @var list<string>
	 */
	private const FREE_WIDGETS = array(
		'heading',
		'image',
		'text-editor',
		'video',
		'button',
		'divider',
		'spacer',
		'google_maps',
		'icon',
		'image-box',
		'icon-box',
		'star-rating',
		'image-carousel',
		'image-gallery',
		'icon-list',
		'counter',
		'progress',
		'testimonial',
		'tabs',
		'accordion',
		'toggle',
		'social-icons',
		'alert',
		'html',
		'shortcode',
		'menu-anchor',
		'sidebar',
	);

	/**
	 * @var list<string>
	 */
	private const CORE_PLUGINS = array(
		'elementor',
		'elementskit-lite',
		'metform',
		'insert-headers-and-footers',
	);

	public const WOO_PLUGIN = 'woocommerce';

	/**
	 * @var list<string>
	 */
	private const SNIPPET_TYPES = array(
		'css',
		'js',
		'html',
	);

	/**
	 * @var array<string,string>
	 */
	private const PLUGIN_MAINS = array(
		'elementor' => 'elementor/elementor.php',
		'elementskit-lite' => 'elementskit-lite/elementskit-lite.php',
		'metform' => 'metform/metform.php',
		'insert-headers-and-footers' => 'insert-headers-and-footers/ihaf.php',
		'woocommerce' => 'woocommerce/woocommerce.php',
	);

	/**
	 * @return list<string>
	 */
	public static function free_widgets(): array {
		return self::FREE_WIDGETS;
	}

	/**
	 * @param string $widget_type Widget type slug.
	 */
	public static function is_free_widget( string $widget_type ): bool {
		return in_array( $widget_type, self::FREE_WIDGETS, true );
	}

	/**
	 * @return list<string>
	 */
	public static function core_plugins(): array {
		return self::CORE_PLUGINS;
	}

	/**
	 * Declared plugin slugs for a package (core + optional Woo).
	 *
	 * @param bool $woo_enabled Whether woocommerce.enabled is true.
	 * @return list<string>
	 */
	public static function declared_plugins( bool $woo_enabled ): array {
		$plugins = self::CORE_PLUGINS;
		if ( $woo_enabled ) {
			$plugins[] = self::WOO_PLUGIN;
		}
		return $plugins;
	}

	/**
	 * @return list<string>
	 */
	public static function snippet_types(): array {
		return self::SNIPPET_TYPES;
	}

	/**
	 * @param string $type Snippet type.
	 */
	public static function is_snippet_type( string $type ): bool {
		return in_array( $type, self::SNIPPET_TYPES, true );
	}

	/**
	 * @return array<string,string>
	 */
	public static function plugin_mains(): array {
		return self::PLUGIN_MAINS;
	}

	/**
	 * @param string $slug Plugin slug.
	 */
	public static function plugin_main( string $slug ): string {
		return self::PLUGIN_MAINS[ $slug ] ?? '';
	}
}
