import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  declaredPlugins,
  parsePackageJson,
  type CtwPackage,
} from "@ctw/schema";

const here = dirname(fileURLToPath(import.meta.url));

/**
 * Locate theme-kit/ from unbundled package paths or the root CLI bundle.
 */
export function loadThemeKitRoot(): string {
  const candidates = [
    join(here, "../../../theme-kit"),
    join(here, "../theme-kit"),
    join(here, "../../theme-kit"),
  ];
  for (const dir of candidates) {
    if (existsSync(join(dir, "style.css"))) {
      return dir;
    }
  }
  throw new Error("theme-kit not found next to the CLI package.");
}

export function styleCss(pkg: CtwPackage): string {
  return `/*
Theme Name: ${pkg.theme.name}
Theme URI: https://github.com/md786-dotcom/claude-to-wordpress-native
Description: Hello Elementor child theme generated by Claude-to-WordPress Native. Parent: Hello Elementor.
Author: Claude-to-WordPress Native
Template: hello-elementor
Version: 1.0.0
Requires at least: 6.0
Requires PHP: 7.4
License: GNU General Public License v2 or later
License URI: https://www.gnu.org/licenses/gpl-2.0.html
Text Domain: ${pkg.theme.slug}
*/

/* Appearance → Customize → Additional CSS remains available. Do not dequeue wp-custom-css. */
`;
}

export function functionsPhp(pkg: CtwPackage): string {
  const primary = pkg.theme.colors.primary ?? "";
  const cssValue =
    primary === "" ? "" : `:root { --ctw-primary: ${primary}; }`;

  return [
    "<?php",
    "/**",
    ` * ${pkg.theme.name} — Hello Elementor child.`,
    " *",
    " * @package CTW_Native_Child",
    " */",
    "",
    "if ( ! defined( 'ABSPATH' ) ) {",
    "\texit;",
    "}",
    "",
    "define( 'CTW_CHILD_VERSION', '1.0.0' );",
    "",
    "/**",
    " * Enqueue parent and child styles. Keep wp_head so Customizer Additional CSS prints.",
    " */",
    "function ctw_child_scripts_styles(): void {",
    "\twp_enqueue_style(",
    "\t\t'hello-elementor-child-style',",
    "\t\tget_stylesheet_uri(),",
    "\t\tarray( 'hello-elementor-theme-style' ),",
    "\t\tCTW_CHILD_VERSION",
    "\t);",
    "}",
    "add_action( 'wp_enqueue_scripts', 'ctw_child_scripts_styles', 20 );",
    "",
    "/**",
    " * Optional design tokens from the package.",
    " */",
    "function ctw_child_inline_tokens(): void {",
    `\t$css = '${cssValue.replace(/'/g, "\\'")}';`,
    "\tif ( '' === $css ) {",
    "\t\treturn;",
    "\t}",
    "\twp_add_inline_style( 'hello-elementor-child-style', $css );",
    "}",
    "add_action( 'wp_enqueue_scripts', 'ctw_child_inline_tokens', 30 );",
    "",
  ].join("\n");
}

export function normalizePlugins(pkg: CtwPackage): CtwPackage {
  return {
    ...pkg,
    plugins: declaredPlugins(pkg),
  };
}

export function readPackageFromJsonText(text: string): CtwPackage {
  const parsed = JSON.parse(text) as { [key: string]: import("@ctw/schema").JsonValue };
  return normalizePlugins(parsePackageJson(parsed));
}

export function readPackageFromFile(path: string): CtwPackage {
  return readPackageFromJsonText(readFileSync(path, "utf8"));
}

export function packageJsonForTheme(pkg: CtwPackage): string {
  return `${JSON.stringify(normalizePlugins(pkg), null, 2)}\n`;
}
